# Generated by Django 5.2.6 on 2025-09-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utente',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='utente',
            name='username',
        ),
    ]
