# Generated by Django 5.2.6 on 2025-09-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateField(verbose_name='Data inizio')),
                ('data_fine', models.DateField(verbose_name='Data fine')),
                ('tipo', models.CharField(choices=[('malattia', 'Malattia'), ('ferie', 'Ferie'), ('permesso', 'Permesso'), ('infortunio', 'Infortunio'), ('altro', 'Altro')], max_length=20, verbose_name='Tipo assenza')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('approvata', models.BooleanField(default=False, verbose_name='Approvata')),
                ('data_approvazione', models.DateTimeField(blank=True, null=True, verbose_name='Data approvazione')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data modifica')),
            ],
            options={
                'verbose_name': 'Assenza',
                'verbose_name_plural': 'Assenze',
                'ordering': ['-data_inizio', '-data_creazione'],
            },
        ),
    ]
