# Generated by Django 5.2.6 on 2025-09-21 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assenza', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assenza',
            name='approvata_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assenze_approvate', to=settings.AUTH_USER_MODEL, verbose_name='Approvata da'),
        ),
        migrations.AddField(
            model_name='assenza',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assenze', to=settings.AUTH_USER_MODEL, verbose_name='Utente'),
        ),
    ]
