# Generated by Django 5.2.6 on 2025-09-21 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assenza', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assenza',
            options={'ordering': ['-dataInizio'], 'verbose_name': 'Assenza', 'verbose_name_plural': 'Assenze'},
        ),
        migrations.AddField(
            model_name='assenza',
            name='dataFine',
            field=models.DateField(blank=True, null=True, verbose_name='Data fine'),
        ),
        migrations.AddField(
            model_name='assenza',
            name='dataInizio',
            field=models.DateField(blank=True, null=True, verbose_name='Data inizio'),
        ),
        migrations.AddField(
            model_name='assenza',
            name='operatore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assenze', to=settings.AUTH_USER_MODEL, verbose_name='Operatore'),
        ),
        migrations.AddField(
            model_name='assenza',
            name='tipoAssenza',
            field=models.CharField(blank=True, choices=[('MALATTIA', 'Malattia'), ('FERIE', 'Ferie'), ('PERMESSO', 'Permesso'), ('ASPETTATIVA', 'Aspettativa'), ('MATERNITA', 'Maternità')], max_length=20, null=True, verbose_name='Tipo assenza'),
        ),
        migrations.AlterField(
            model_name='assenza',
            name='approvata',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Approvata'),
        ),
        migrations.AlterField(
            model_name='assenza',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data creazione'),
        ),
        migrations.AlterField(
            model_name='assenza',
            name='data_fine',
            field=models.DateField(blank=True, null=True, verbose_name='Data fine'),
        ),
        migrations.AlterField(
            model_name='assenza',
            name='data_inizio',
            field=models.DateField(blank=True, null=True, verbose_name='Data inizio'),
        ),
        migrations.AlterField(
            model_name='assenza',
            name='data_modifica',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data modifica'),
        ),
        migrations.AlterField(
            model_name='assenza',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo assenza'),
        ),
        migrations.AlterField(
            model_name='assenza',
            name='utente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assenze_vecchie', to=settings.AUTH_USER_MODEL, verbose_name='Utente'),
        ),
    ]
