# Generated by Django 5.2.6 on 2025-09-21 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mezzo', '0001_initial'),
        ('rimorchio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MezzoRimorchio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAttivo', models.BooleanField(default=True, verbose_name='È attivo')),
                ('data_associazione', models.DateTimeField(auto_now_add=True, verbose_name='Data associazione')),
                ('data_dissociazione', models.DateTimeField(blank=True, null=True, verbose_name='Data dissociazione')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data modifica')),
                ('mezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mezzoRimorchio', to='mezzo.mezzo', verbose_name='Mezzo')),
                ('rimorchio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mezzoRimorchio', to='rimorchio.rimorchio', verbose_name='Rimorchio')),
            ],
            options={
                'verbose_name': 'Associazione Mezzo-Rimorchio',
                'verbose_name_plural': 'Associazioni Mezzo-Rimorchio',
                'ordering': ['-data_associazione'],
            },
        ),
    ]
