# Generated by Django 5.2.6 on 2025-09-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mezzo_rimorchio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mezzorimorchio',
            name='isAttivo',
        ),
    ]
