# Generated by Django 5.2.6 on 2025-09-21 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mezzo_rimorchio', '0002_remove_mezzorimorchio_isattivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mezzorimorchio',
            name='note',
        ),
    ]
