# Generated by Django 5.2.6 on 2025-09-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome documento')),
                ('tipo', models.CharField(choices=[('PATENTE', 'Patente'), ('CARTA_IDENTITA', "Carta d'identità"), ('FORMULARIO', 'Formulario'), ('FATTURA', 'Fattura'), ('CONTRATTO', 'Contratto'), ('ASSICURAZIONE', 'Assicurazione'), ('REVISIONE', 'Revisione'), ('ALTRO', 'Altro')], default='ALTRO', max_length=30, verbose_name='Tipo documento')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('data_caricamento', models.DateTimeField(auto_now_add=True, verbose_name='Data caricamento')),
                ('data_scadenza', models.DateField(blank=True, null=True, verbose_name='Data scadenza')),
                ('file', models.FileField(blank=True, null=True, upload_to='documenti/', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documenti',
                'ordering': ['-data_caricamento'],
            },
        ),
    ]
