# Generated by Django 5.2.6 on 2025-09-21 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0003_rename_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='dataInserimento',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data inserimento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='operatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to=settings.AUTH_USER_MODEL, verbose_name='Operatore'),
        ),
    ]
