# Generated by Django 5.2.6 on 2025-09-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0004_alter_documento_datainserimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipoDocumento',
            field=models.CharField(choices=[('FIR', 'Fir'), ('CORSO_SICUREZZA', 'Corso sulla sicurezza'), ('CORSO_AGGIORNAMENTO', "Corso d'aggiornamento"), ('ALTRO', 'Altro')], default='ALTRO', max_length=30, verbose_name='Tipo documento'),
        ),
    ]
