# Generated by Django 5.2.6 on 2025-09-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0006_remove_documento_nome_alter_documento_tipodocumento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='descrizione',
        ),
    ]
