# Generated by Django 5.2.6 on 2025-10-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0008_alter_documento_operatore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='dataScadenza',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data scadenza (data e ora)'),
        ),
    ]
