# Generated by Django 5.2.6 on 2025-09-21 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attivita', '0004_remove_attivita_stato_remove_attivita_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UtenteAttivita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assegnazione', models.DateTimeField(auto_now_add=True, verbose_name='Data assegnazione')),
                ('attivita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utente_attivita', to='attivita.attivita', verbose_name='Attività')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utente_attivita', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Associazione Utente-Attività',
                'verbose_name_plural': 'Associazioni Utente-Attività',
                'unique_together': {('utente', 'attivita')},
            },
        ),
    ]
