# Generated by Django 5.2.6 on 2025-09-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attivita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('stato', models.CharField(choices=[('PIANIFICATA', 'Pianificata'), ('IN_CORSO', 'In corso'), ('COMPLETATA', 'Completata'), ('ANNULLATA', 'Annullata'), ('SOSPESA', 'Sospesa')], default='PIANIFICATA', max_length=20, verbose_name='Stato attività')),
                ('data_inizio_pianificata', models.DateTimeField(verbose_name='Data inizio pianificata')),
                ('data_fine_pianificata', models.DateTimeField(verbose_name='Data fine pianificata')),
                ('data_inizio_effettiva', models.DateTimeField(blank=True, null=True, verbose_name='Data inizio effettiva')),
                ('data_fine_effettiva', models.DateTimeField(blank=True, null=True, verbose_name='Data fine effettiva')),
                ('indirizzo_partenza', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indirizzo partenza')),
                ('indirizzo_destinazione', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indirizzo destinazione')),
                ('priorita', models.PositiveSmallIntegerField(default=1, verbose_name='Priorità')),
                ('completamento', models.PositiveSmallIntegerField(default=0, verbose_name='Percentuale completamento')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data modifica')),
            ],
            options={
                'verbose_name': 'Attività',
                'verbose_name_plural': 'Attività',
                'ordering': ['-data_inizio_pianificata', 'priorita'],
            },
        ),
    ]
