# Generated by Django 5.2.6 on 2025-09-21 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attivita', '0001_initial'),
        ('documento', '0001_initial'),
        ('mezzo_rimorchio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='documenti',
            field=models.ManyToManyField(blank=True, related_name='attivita', to='documento.documento', verbose_name='Documenti'),
        ),
        migrations.AddField(
            model_name='attivita',
            name='mezzo_rimorchio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attivita', to='mezzo_rimorchio.mezzorimorchio', verbose_name='Mezzo e Rimorchio'),
        ),
    ]
