# Generated by Django 5.2.6 on 2025-09-21 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attivita', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='utente_creatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attivita_create', to=settings.AUTH_USER_MODEL, verbose_name='Utente creatore'),
        ),
        migrations.AddField(
            model_name='attivita',
            name='utenti_assegnati',
            field=models.ManyToManyField(blank=True, related_name='attivita_assegnate', to=settings.AUTH_USER_MODEL, verbose_name='Utenti assegnati'),
        ),
    ]
