# Generated by Django 5.2.6 on 2025-09-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attivita', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attivita',
            name='stato',
        ),
        migrations.RemoveField(
            model_name='attivita',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='attivita',
            name='utenti_assegnati',
        ),
        migrations.AddField(
            model_name='attivita',
            name='statoAttivita',
            field=models.CharField(choices=[('PROGRAMMATA', 'Programmata'), ('INIZIATA', 'Iniziata'), ('TERMINATA', 'Terminata')], default='PROGRAMMATA', max_length=20, verbose_name='Stato attività'),
        ),
    ]
