# Generated by Django 5.2.6 on 2025-09-21 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attivita', '0004_remove_attivita_stato_remove_attivita_tipo_and_more'),
        ('utente_attivita', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='utenti',
            field=models.ManyToManyField(related_name='attivita', through='utente_attivita.UtenteAttivita', to=settings.AUTH_USER_MODEL, verbose_name='Utenti assegnati'),
        ),
    ]
