# Generated by Django 5.2.6 on 2025-09-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attivita', '0005_attivita_utenti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attivita',
            name='utenti',
        ),
    ]
