# Generated by Django 5.2.6 on 2025-09-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attivita', '0006_remove_attivita_utenti'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attivita',
            options={'ordering': ['-data'], 'verbose_name': 'Attività', 'verbose_name_plural': 'Attività'},
        ),
        migrations.RemoveField(
            model_name='attivita',
            name='completamento',
        ),
        migrations.RemoveField(
            model_name='attivita',
            name='data_fine_effettiva',
        ),
        migrations.RemoveField(
            model_name='attivita',
            name='data_fine_pianificata',
        ),
        migrations.RemoveField(
            model_name='attivita',
            name='data_inizio_effettiva',
        ),
        migrations.RemoveField(
            model_name='attivita',
            name='data_inizio_pianificata',
        ),
        migrations.RemoveField(
            model_name='attivita',
            name='indirizzo_destinazione',
        ),
        migrations.RemoveField(
            model_name='attivita',
            name='indirizzo_partenza',
        ),
        migrations.RemoveField(
            model_name='attivita',
            name='priorita',
        ),
        migrations.AddField(
            model_name='attivita',
            name='codiceCer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codice CER'),
        ),
        migrations.AddField(
            model_name='attivita',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Inizio'),
        ),
        migrations.AddField(
            model_name='attivita',
            name='luogo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Luogo'),
        ),
    ]
