# Generated by Django 5.2.6 on 2025-09-21 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attivita', '0007_alter_attivita_options_remove_attivita_completamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attivita',
            name='note',
        ),
    ]
