# Generated by Django 5.2.6 on 2025-09-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attivita', '0008_remove_attivita_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='durata',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durata (ore)'),
        ),
    ]
