# Generated by Django 5.2.6 on 2025-09-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attivita', '0009_attivita_durata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attivita',
            name='durata',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durata (minuti)'),
        ),
    ]
