# Generated by Django 5.2.6 on 2025-09-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rimorchio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rimorchio',
            options={'ordering': ['nome'], 'verbose_name': 'Rimorchio', 'verbose_name_plural': 'Rimorchi'},
        ),
        migrations.RemoveField(
            model_name='rimorchio',
            name='anno',
        ),
        migrations.RemoveField(
            model_name='rimorchio',
            name='assicurazione_scadenza',
        ),
        migrations.RemoveField(
            model_name='rimorchio',
            name='attivo',
        ),
        migrations.RemoveField(
            model_name='rimorchio',
            name='capacita',
        ),
        migrations.RemoveField(
            model_name='rimorchio',
            name='data_creazione',
        ),
        migrations.RemoveField(
            model_name='rimorchio',
            name='data_modifica',
        ),
        migrations.RemoveField(
            model_name='rimorchio',
            name='lunghezza',
        ),
        migrations.RemoveField(
            model_name='rimorchio',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='rimorchio',
            name='modello',
        ),
        migrations.RemoveField(
            model_name='rimorchio',
            name='note',
        ),
        migrations.RemoveField(
            model_name='rimorchio',
            name='revisione_scadenza',
        ),
        migrations.RemoveField(
            model_name='rimorchio',
            name='targa',
        ),
        migrations.RemoveField(
            model_name='rimorchio',
            name='tipo',
        ),
        migrations.AddField(
            model_name='rimorchio',
            name='capacitaDiCarico',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Capacità di Carico'),
        ),
        migrations.AddField(
            model_name='rimorchio',
            name='nome',
            field=models.CharField(default='Rimorchio', max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='rimorchio',
            name='tipoRimorchio',
            field=models.CharField(choices=[('RIBALTABILE', 'Ribaltabile'), ('COMPATTANTE', 'Compattante'), ('CISTERNA', 'Cisterna'), ('PIANALE', 'Pianale'), ('CASSONE', 'Cassone'), ('SCARRABILE', 'Scarrabile'), ('ALTRO', 'Altro')], default='ALTRO', max_length=20, verbose_name='Tipo Rimorchio'),
        ),
    ]
