# Generated by Django 5.2.6 on 2025-10-05 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rimorchio', '0002_alter_rimorchio_options_remove_rimorchio_anno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rimorchio',
            name='data_creazione',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data creazione'),
        ),
        migrations.AddField(
            model_name='rimorchio',
            name='data_modifica',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modifica'),
        ),
    ]
