# Generated by Django 5.2.6 on 2025-10-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rimorchio', '0003_rimorchio_data_creazione_rimorchio_data_modifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='rimorchio',
            name='immagine',
            field=models.FileField(blank=True, help_text="Carica un'immagine del rimorchio (formati supportati: JPG, PNG)", null=True, upload_to='rimorchi/immagini/', verbose_name='Immagine del rimorchio'),
        ),
    ]
