# Generated by Django 5.2.6 on 2025-09-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targa', models.CharField(max_length=20, unique=True, verbose_name='Targa')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modello', models.CharField(max_length=50, verbose_name='Modello')),
                ('anno', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Anno')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('capacita', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacità')),
                ('chilometraggio', models.PositiveIntegerField(default=0, verbose_name='Chilometraggio')),
                ('revisione_scadenza', models.DateField(blank=True, null=True, verbose_name='Scadenza revisione')),
                ('assicurazione_scadenza', models.DateField(blank=True, null=True, verbose_name='Scadenza assicurazione')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data modifica')),
            ],
            options={
                'verbose_name': 'Mezzo',
                'verbose_name_plural': 'Mezzi',
                'ordering': ['targa'],
            },
        ),
    ]
