# Generated by Django 5.2.6 on 2025-09-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mezzo',
            old_name='assicurazione_scadenza',
            new_name='scadenzaAssicurazione',
        ),
        migrations.RenameField(
            model_name='mezzo',
            old_name='revisione_scadenza',
            new_name='scadenzaRevisione',
        ),
        migrations.RemoveField(
            model_name='mezzo',
            name='anno',
        ),
        migrations.RemoveField(
            model_name='mezzo',
            name='attivo',
        ),
        migrations.RemoveField(
            model_name='mezzo',
            name='capacita',
        ),
        migrations.RemoveField(
            model_name='mezzo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='mezzo',
            name='modello',
        ),
        migrations.RemoveField(
            model_name='mezzo',
            name='note',
        ),
        migrations.RemoveField(
            model_name='mezzo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='mezzo',
            name='consumoCarburante',
            field=models.PositiveIntegerField(default=0, verbose_name='Consumo carburante'),
        ),
        migrations.AddField(
            model_name='mezzo',
            name='isDanneggiato',
            field=models.BooleanField(default=False, verbose_name='È danneggiato'),
        ),
        migrations.AddField(
            model_name='mezzo',
            name='statoMezzo',
            field=models.CharField(choices=[('DISPONIBILE', 'Disponibile'), ('OCCUPATO', 'Occupato'), ('MANUTENZIONE', 'In manutenzione')], default='DISPONIBILE', max_length=20, verbose_name='Stato del mezzo'),
        ),
    ]
