# Generated by Django 5.2.6 on 2025-09-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzo', '0002_rename_assicurazione_scadenza_mezzo_scadenzaassicurazione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezzo',
            name='immagine',
            field=models.FileField(blank=True, help_text="Carica un'immagine del mezzo (formati supportati: JPG, PNG)", null=True, upload_to='mezzi/immagini/', verbose_name='Immagine del mezzo'),
        ),
    ]
